prod: removed executable permission from setenv and added an error message if it is executed directly
setenv is intended to be sourced and not executed directly

diff --git a/setenv b/setenv
--- a/setenv
+++ b/setenv
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/usr/bin/env -S sh -c "echo >&2 \"Error: You are running this script instead of sourcing it. Make sure to use it as 'source setenv' or '. setenv', otherwise its settings won't take effect.\"; exit 1"
 
 case "$-" in
 *i*) ;;
